name: hive_cache_interceptor
description: Package to implements cache using hive in hasura_connect package
version: 1.0.0-dev.2
author: F-Team <david@flutterando.com.br>
homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/hive_cache_interceptor

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.26.0-17.5.pre <2.0.0"

dependencies:
  hive_flutter: 1.0.0-nullsafety.0
  hive: ^1.6.0-nullsafety.2
  dartz: ^0.10.0-nullsafety.1
  hasura_cache_interceptor: 
    git:
      url: https://github.com/OrlandoEduardo101/hasura_cache_interceptor.git
      ref: fc937cba7867d7591f0155c757bc27e86e4699d2
  flutter:
    sdk: flutter

dev_dependencies:
  #mockito: ^4.1.1
  mocktail: ^0.0.1-dev.11
  flutter_test:
    sdk: flutter

flutter:
